export enum SectorOfActivities {
    CONSTRUCTION = 'construction',
    TRANSPORT = 'transport',
    EDUCATION = 'education',
    AGRICULTURE_AND_FISHING = 'agricultureAndFishing',
    MINING = 'mining',
    REAL_ESTATE = 'realEstate',
    ENTERTAINMENT_AND_RECREATION = 'entertainmentAndRecreation',
    HEALTH_CARE = 'healthCare',
    MANUFACTURING = 'manufacturing',
    UTILITIES = 'utilities',
    INDUSTRY = 'industry',
    INFORMATION_AND_COMMUNICATIONS_TECHNOLOGY = 'informationAndCommunicationsTechnology',
    WHOLESALE_TRADE = 'WholesaleTrade',
    ADMINISTRATIVE_AND_SUPPORT_AND_WASTE_MANAGEMENT = 'administrativeAndSupportAndWasteManagement',
    INDUSTRIALS = 'industrials',
    CONSUMER_DISCRETIONARY = 'consumerDiscretionary',
    IT = 'it',
    PRIMARY_SECTOR = 'primarySector',
    FINANCE_AND_INSURANCE = 'financeAndInsurance',
    ACCOMMODATION_AND_FOOD_SERVICES = 'accommodationAndFoodServices',
    PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL_SERVICES = 'professionalScientificAndTechnicalServices',
    RETAIL_TRADE = 'retailTrade',
    FINANCIAL_ACTIVITIES = 'financialActivities',
    OTHER_SERVICES = 'otherServices'
}
